config/routes.rb
Rails.application.routes.draw do
  root  'homes#top'
  resources :lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
    validates :title, presence: true
    validates :body, presence: true
end

app/models/list.rb
class List < ApplicationRecord
    
    validates :title, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @list = List.new
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
  end
  
  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list), flash: { notice: 'Book was successfully created.'}
    else
      @lists = List.all
      render :index
    end
  end

  def edit
    @list = List.find(params[:id])
  end
  
  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to list_path(@list), flash: { notice: 'Book was successfully changed.'}
    else
      render :edit
    end
  end
  
  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to lists_path
  end
  
  private
  def list_params
    params.require(:list).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
  </head>

  <body>
    <h1>ようこそ <strong>Bookers</strong>  へ！</h1>
    <p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p>
    <p>印象を共有し交換することができます</p>
    <p><%= link_to "Start", lists_path %></p>    	
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBookers</title>
  </head>

  <body>
    
    <% if flash[:notice] %>
      <%= notice %>
    <% end %>
    
    <% if @list.errors.any? %>
      <%= @list.errors.count %>errors prohibited this book from being saved:
      <% @list.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
    
    <h1>Editing Book</h1>

    <%= form_with model:@list, local: true do |f| %>
      <h4>Title</h4>
      <%= f.text_field :title %>
      
      <h4>Body</h4>
      <%= f.text_area :body %>
      
      <%= f.submit 'Update List' %>
    
      <%= link_to "Show", list_path(@list)%>  | 
      <%= link_to "Back", lists_path %>
      
    <% end %>
  </body>
</html>

app/views/lists/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
  </head>


  <body>

    <h1>Books</h1>
    
    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Body</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @lists.each do |list| %>
        <tr>
          <td><%= list.title %></td>
          <td><%= list.body %></td>
          <td><%= link_to "Show", list_path(list)%></td>
          <td><%= link_to "Edit", edit_list_path(list) %></td>
          <td><%= link_to "Destroy", list_path(list),method: :delete %></td>
        </tr>
        <% end %>
          
      </tbody>
    </table>
    
    <%if @list.errors.any? %>
      <%= @list.errors.count %>errors prohibited this book from being saved:
      <% @list.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
    
    <h2>New book</h2>
    <%= form_with model:@list, local:true do |f| %>

      <div class="field">
        <%= f.text_field :title %>
      </div>
    
      <div class="field">
        <%= f.text_area :body %>
      </div>
    
      <div class="actions">
        <%= f.submit 'Create List' %>
      </div>
    <% end %>
  </body>
</html>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

app/views/lists/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBookers</title>
  </head>

  <body>
    
    <% if flash[:notice] %>
      <%= notice %>
    <% end %>

    <p>
      <strong>Title:</strong>
      <%= @list.title %>
    </p>
    
    <p>
      <strong>Body:</strong>
      <%= @list.body %>
    </p>
    
    <%= link_to "Edit", edit_list_path(@list) %>
    <%= link_to "Back", lists_path %>

  </body>
</html>